repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: autopep8-wrapper
      - id: end-of-file-fixer
      - id: flake8
      - id: requirements-txt-fixer
      - id: trailing-whitespace
